# Pandas 数据分析

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## 创建数据表

In [ ]:
df1 = pd.DataFrame(data=[[1,2,3],[4,5,6]],
                   index=['row1','row2'],
                   columns=['c1','c2','c3'])

dates = pd.date_range('2020-08-01',periods=7)
df2 = pd.DataFrame(np.random.randn(7,4),
                   index=dates,
                   columns=list('abcd'))

df3 = pd.DataFrame({'a':[1,2,3],'b':[4,5,6]})

df4 = pd.DataFrame({"Beijing":{'2017':1,'2018':2},
                    "Shanghai":{'2017':3,'2018':4}})

a1 = pd.Series(range(5))
b1 = pd.Series(np.linspace(4,20,5))
df5 = pd.concat([a1,b1],axis=1)

df6 = pd.DataFrame()
index = list('abcde')
for i in range(5):
    ai = pd.DataFrame(data=[np.linspace(i,5*i,5)],index=[index[i]])
    df6 = df6.append(ai)

(df6.iloc[1,2],df6.iat[1,3])

# df6.drop(index='a',inplace=True)
df6 = df6.reindex(columns=list('12345'))

## 数据清洗

In [2]:
df1 = pd.read_excel('./data/data1.xlsx', index_col=r"时间")
df2 = pd.read_excel('./data/data2.xlsx', index_col=r"时间")
df3 = pd.read_excel('./data/data3.xlsx', index_col=r"时间")

In [4]:
df1.head(n=10)

,GPS车速,X轴加速度,Y轴加速度,Z轴加速度,经度,纬度,发动机转速,扭矩百分比,瞬时油耗,油门踏板开度,空燃比,发动机负荷百分比,进气流量
时间,,,,,,,,,,,,,
2017/12/18 13:42:13.000.,0.0,0.0,-0.396,-0.900,119.367781,25.992420,775,18,58.02,0.00,0.1465,22,2.30
2017/12/18 13:42:14.000.,0.0,0.0,-0.378,-0.882,119.367783,25.992418,775,17,60.30,0.00,0.1465,21,2.39
2017/12/18 13:42:15.000.,0.0,0.0,-0.396,-0.882,119.367785,25.992416,775,17,55.24,0.00,0.1464,22,2.19
2017/12/18 13:42:16.000.,0.0,0.0,-0.378,-0.900,119.367785,25.992416,762,17,55.75,0.00,0.1471,21,2.21
2017/12/18 13:42:17.000.,0.0,0.0,-0.396,-0.882,119.367785,25.992416,762,16,56.00,0.00,0.1471,21,2.22
2017/12/18 13:42:18.000.,0.0,0.0,-0.378,-0.900,119.367785,25.992416,787,18,63.33,0.00,0.1471,22,2.51
2017/12/18 13:42:19.000.,0.0,0.0,-0.342,-0.936,119.367785,25.992416,687,21,62.06,0.05,0.1471,26,2.46
2017/12/18 13:42:20.000.,0.0,0.0,-0.324,-0.936,119.367785,25.992416,900,25,0.36,0.08,0.1470,31,3.79
2017/12/18 13:42:21.000.,4.5,0.0,-0.324,-0.918,119.367791,25.992408,1025,25,0.44,0.08,0.1467,32,4.51
2017/12/18 13:42:22.000.,6.9,0.0,-0.324,-0.936,119.367801,25.992398,1137,26,0.46,0.08,0.1466,32,4.70

In [34]:
df1.columns = ['GPS', 'AX', 'AY', 'AZ', 'JD', 'WD', 'VW', 'PN', 'PH', 'OP', 'AP', 'PP', 'AF']
# df1['GPS'][0:50000].mean()
df1[df1['AY']==0]

,GPS,AX,AY,AZ,JD,WD,VW,PN,PH,OP,AP,PP,AF
时间,,,,,,,,,,,,,
2017/12/18 22:52:16.000.,44.3,0.144,0.0,-0.792,119.621410,25.922166,1550,39,0.96,0.115,0.1466,45,9.88
2017/12/19 18:07:46.000.,33.8,0.234,0.0,-1.350,119.563141,26.157649,925,18,0.26,0.000,0.1463,24,2.81
2017/12/23 10:23:13.000.,46.6,0.000,0.0,-0.918,119.658624,25.911670,1100,13,63.84,0.000,0.1454,16,2.53